[config]

[templates.dmsgtk4]
input_path = './matugen/templates/gtk-colors.css'
output_path = '~/.config/gtk-4.0/dank-colors.css'

[templates.dmskcolorscheme]
input_path = './matugen/templates/kcolorscheme.colors'
output_path = '~/.local/share/color-schemes/DankMatugen.colors'

[templates.dmslightkcolorscheme]
input_path = './matugen/templates/light-kcolorscheme.colors'
output_path = '~/.local/share/color-schemes/DankMatugenLight.colors'

[templates.dmsdarkkcolorscheme]
input_path = './matugen/templates/dark-kcolorscheme.colors'
output_path = '~/.local/share/color-schemes/DankMatugenDark.colors'